In [3]:
import numpy as np
import sys

In [2]:
np.array

numpy.int8

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1,2,3,4])

In [6]:
b = np.array([0, .5, 1, 1.5, 2])

In [8]:
a[0], a[1]

(1, 2)

In [9]:
b[0], b[2], b[-1] # calling multiple indexes at thesame time

(0.0, 1.0, 2.0)

In [12]:
b[[0,2,-1]] # this will create another numppy array

array([0., 1., 2.])

### Array Types

In [16]:
a

array([1, 2, 3, 4])

In [17]:
a.dtype #to check the array types in numpy

dtype('int32')

In [18]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
b.dtype

dtype('float64')

In [20]:
# to convert to a specific arrary type

In [29]:
np.array([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [30]:
c = np.array(['a', 'b', 'c'])

In [31]:
c.dtype

dtype('<U1')

### Dimensions and shapes

In [56]:
# .shape will tell us how many rows and colume we have in an nested array
new = np.array([
    [1, 2, 3],
    [4,5,6],
    [7,8,9]
])

In [36]:
new.shape

(2, 3)

In [38]:
new.ndim # ndim is dimenision, how many vertical and horizontal

2

In [39]:
new.size # size is total values in an array

6

In [42]:
B = np.array([
    [
        [11, 10, 9],
        [7,6,5],
    ],
    [
    [50,51,52,],
    [48,45,44]
    ]
])

In [43]:
B

array([[[11, 10,  9],
        [ 7,  6,  5]],

       [[50, 51, 52],
        [48, 45, 44]]])

In [44]:
B.shape

(2, 2, 3)

In [45]:
B.size

12

In [46]:
B.ndim

3

#### Slicing

In [47]:
new[1]

array([4, 5, 6])

In [48]:
new[0]

array([1, 2, 3])

In [51]:
new[0][2]

3

In [53]:
new[1, 2]

6

In [58]:
new

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
new[2,1]

8

In [63]:
new[1:2]

array([[4, 5, 6]])

In [66]:
new.sum()

45

In [67]:
new.std()

2.581988897471611

In [68]:
new.sum(axis=0) # axis 0 is for vertical

array([12, 15, 18])

In [69]:
new.sum(axis=1)  # axis 1 is for horizontal

array([ 6, 15, 24])

In [71]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]
